- icon: "ion-social-usd"
  title: "Kasinos"
  content: "Das neueste und beste Casino"
  link: "https://www.bestecasinosdeutschland.de/casino#rating"

- icon: "ion-ios-game-controller-b"
  title: "Spiele"
  content: "Die beste Auswahl und Vergleich von Spielen"
  link: "https://www.bestecasinosdeutschland.de/casino#rating"

- icon: "ion-ios-star"
  title: "Boni"
  content: "Top-Boni"
  link: "https://www.bestecasinosdeutschland.de/casino#rating"

- icon: "ion-card"
  title: "Zahlungsarten"
  content: "Die beliebtesten Angebote"
  link: "https://www.bestecasinosdeutschland.de/casino#rating"

- icon: "ion-ios-paper"
  title: "Software"
  content: "Reite Palette von Software"
  link: "https://www.bestecasinosdeutschland.de/casino#rating"

- icon: "ion-ios-book"
  title: "Blog"
  content: "Aktives und aktuelles Blog"
  link: "https://www.bestecasinosdeutschland.de/casino#rating"
